In [ ]:
import pandas as pd
import numpy as np

In [34]:
df2 = pd.read_csv('./data/HousePrice_df2')
df2.head()

Unnamed: 0 Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  \
0           0      PConc       Gd       TA           No          GLQ   
1           1     CBlock       Gd       TA           Gd          ALQ   
2           2      PConc       Gd       TA           Mn          GLQ   
3           3     BrkTil       TA       Gd           No          ALQ   
4           4      PConc       Gd       TA           Av          GLQ   

   BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF      ...       LowQualFinSF  \
0         706          Unf           0        150      ...                  0   
1         978          Unf           0        284      ...                  0   
2         486          Unf           0        434      ...                  0   
3         216          Unf           0        540      ...                  0   
4         655          Unf           0        490      ...                  0   

  GrLivArea BsmtFullBath BsmtHalfBath FullBath  HalfBath  BedroomAbvGr  \
0      1710            1            0        2         1             3   
1      1262            0            1        2         0             3   
2      1786            1            0        2         1             3   
3      1717            1            0        1         0             3   
4      2198            1            0        2         1             4   

   KitchenAbvGr  KitchenQual  TotRmsAbvGrd  
0             1           Gd             8  
1             1           TA             6  
2             1           Gd             6  
3             1           Gd             7  
4             1           Gd             9  

[5 rows x 27 columns]

In [21]:
# 카테고리형 피처 칼럼 선별
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 27 columns):
Unnamed: 0      1460 non-null int64
Foundation      1460 non-null object
BsmtQual        1423 non-null object
BsmtCond        1423 non-null object
BsmtExposure    1422 non-null object
BsmtFinType1    1423 non-null object
BsmtFinSF1      1460 non-null int64
BsmtFinType2    1422 non-null object
BsmtFinSF2      1460 non-null int64
BsmtUnfSF       1460 non-null int64
TotalBsmtSF     1460 non-null int64
Heating         1460 non-null object
HeatingQC       1460 non-null object
CentralAir      1460 non-null object
Electrical      1459 non-null object
1stFlrSF        1460 non-null int64
2ndFlrSF        1460 non-null int64
LowQualFinSF    1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
KitchenAbvGr    146

In [30]:
df2[df2['Electrical'].isnull() == True]

Unnamed: 0 Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  \
1379        1379      PConc       Gd       TA           No          Unf   

      BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF      ...       \
1379           0          Unf           0        384      ...        

      LowQualFinSF GrLivArea BsmtFullBath BsmtHalfBath FullBath  HalfBath  \
1379             0      1394            0            0        2         1   

      BedroomAbvGr  KitchenAbvGr  KitchenQual  TotRmsAbvGrd  
1379             3             1           Gd             7  

[1 rows x 27 columns]

``` txt
Foundation      1460 non-null object Categorical
BsmtQual        1423 non-null object Ordinal, NA=0
BsmtCond        1423 non-null object Ordinal, NA=0
BsmtExposure    1422 non-null object Ordinal, NA=0
BsmtFinType1    1423 non-null object Ordinal, NA=0
BsmtFinSF1      1460 non-null int64 
BsmtFinType2    1422 non-null object Ordinal, NA=0
BsmtFinSF2      1460 non-null int64
BsmtUnfSF       1460 non-null int64
TotalBsmtSF     1460 non-null int64
Heating         1460 non-null object Categorical
HeatingQC       1460 non-null object Ordinal
CentralAir      1460 non-null object Categorical
Electrical      1459 non-null object Categorical
1stFlrSF        1460 non-null int64
2ndFlrSF        1460 non-null int64
LowQualFinSF    1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
KitchenAbvGr    1460 non-null int64
KitchenQual     1460 non-null object Ordinal
TotRmsAbvGrd    1460 non-null int64
```

In [ ]:
# temp_dict = {['a', 'b']:[1,2]}
# temp_dict.keys() = df2['Foundation'].unique()
# temp_dict.keys() = ['a', 'b']
# temp_dict.values() = (1,2)
# temp_dict
val = 1
for unique in df2['Foundation'].unique():
    df2['Foundation'][df2['Foundation'] == unique] = val
    val += 1
df2['Foundation']

In [36]:
cols_categorical = ['Foundation','Heating', 'CentralAir', 'Electrical']
for col in df2[cols_categorical]:
    val = 1
    temp_dict = {}
    for unique in df2[col].unique():
        print(unique)
        if unique == 'nan':
            continue
        else:
            temp_dict[unique] = val
            df2[col][df2[col] == unique] = val
            val += 1
    print(temp_dict)
df2[cols_categorical].head()
# df2.loc[:,['Foundation','Heating', 'CentralAir', 'Electrical']]

PConc
CBlock
BrkTil
Wood
Slab
Stone


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


{'PConc': 1, 'CBlock': 2, 'BrkTil': 3, 'Wood': 4, 'Slab': 5, 'Stone': 6}
GasA
GasW
Grav
Wall
OthW
Floor
{'GasA': 1, 'GasW': 2, 'Grav': 3, 'Wall': 4, 'OthW': 5, 'Floor': 6}
Y
N
{'Y': 1, 'N': 2}
SBrkr
FuseF
FuseA
FuseP
Mix
nan
{'SBrkr': 1, 'FuseF': 2, 'FuseA': 3, 'FuseP': 4, 'Mix': 5, nan: 6}


Foundation Heating CentralAir Electrical
0          1       1          1          1
1          2       1          1          1
2          1       1          1          1
3          3       1          1          1
4          1       1          1          1

In [ ]:
df2_categorical = df2[['Foundation','Heating', 'CentralAir', 'Electrical']]
for col in df2_categorical:
    val = 1
    for unique in df2[col]:
        df2[col][df2[col] == unique] = val
        val += 1
df2_categorical
# df2.loc[:,['Foundation','Heating', 'CentralAir', 'Electrical']]

In [ ]:
df2[cols_categorical]