In [5]:
import pandas as pd
import numpy as np

In [59]:
df2 = pd.read_csv('./data/HousePrice_df2')
df2.head()

Unnamed: 0 Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  \
0           0      PConc       Gd       TA           No          GLQ   
1           1     CBlock       Gd       TA           Gd          ALQ   
2           2      PConc       Gd       TA           Mn          GLQ   
3           3     BrkTil       TA       Gd           No          ALQ   
4           4      PConc       Gd       TA           Av          GLQ   

   BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF      ...       LowQualFinSF  \
0         706          Unf           0        150      ...                  0   
1         978          Unf           0        284      ...                  0   
2         486          Unf           0        434      ...                  0   
3         216          Unf           0        540      ...                  0   
4         655          Unf           0        490      ...                  0   

  GrLivArea BsmtFullBath BsmtHalfBath FullBath  HalfBath  BedroomAbvGr  \
0      1710            1            0        2         1             3   
1      1262            0            1        2         0             3   
2      1786            1            0        2         1             3   
3      1717            1            0        1         0             3   
4      2198            1            0        2         1             4   

   KitchenAbvGr  KitchenQual  TotRmsAbvGrd  
0             1           Gd             8  
1             1           TA             6  
2             1           Gd             6  
3             1           Gd             7  
4             1           Gd             9  

[5 rows x 27 columns]

## 데이터 타입 분류

In [60]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 27 columns):
Unnamed: 0      1460 non-null int64
Foundation      1460 non-null object
BsmtQual        1423 non-null object
BsmtCond        1423 non-null object
BsmtExposure    1422 non-null object
BsmtFinType1    1423 non-null object
BsmtFinSF1      1460 non-null int64
BsmtFinType2    1422 non-null object
BsmtFinSF2      1460 non-null int64
BsmtUnfSF       1460 non-null int64
TotalBsmtSF     1460 non-null int64
Heating         1460 non-null object
HeatingQC       1460 non-null object
CentralAir      1460 non-null object
Electrical      1459 non-null object
1stFlrSF        1460 non-null int64
2ndFlrSF        1460 non-null int64
LowQualFinSF    1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
KitchenAbvGr    146

``` txt
Foundation      1460 non-null object Categorical
BsmtQual        1423 non-null object Ordinal, NA=0
BsmtCond        1423 non-null object Ordinal, NA=0
BsmtExposure    1422 non-null object Ordinal, NA=0
BsmtFinType1    1423 non-null object Ordinal, NA=0
BsmtFinSF1      1460 non-null int64 
BsmtFinType2    1422 non-null object Ordinal, NA=0
BsmtFinSF2      1460 non-null int64
BsmtUnfSF       1460 non-null int64
TotalBsmtSF     1460 non-null int64
Heating         1460 non-null object Categorical
HeatingQC       1460 non-null object Ordinal
CentralAir      1460 non-null object Categorical
Electrical      1459 non-null object Categorical
1stFlrSF        1460 non-null int64
2ndFlrSF        1460 non-null int64
LowQualFinSF    1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
KitchenAbvGr    1460 non-null int64
KitchenQual     1460 non-null object Ordinal
TotRmsAbvGrd    1460 non-null int64
```

In [20]:
cols_numerical = []
for col in df2:
    if df2[col].dtype == 'int64':
        cols_numerical.append(col)
cols_numerical = cols_numerical[1:]
cols_ordinal = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'KitchenQual']
cols_categorical = ['Foundation','Heating', 'CentralAir', 'Electrical']

## 이상치 처리
모델링 후 진행

## 결측치 처리


In [45]:
df2[cols_numerical].info()
df2[cols_categorical].info()
df2[cols_ordinal].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 15 columns):
BsmtFinSF1      1460 non-null int64
BsmtFinSF2      1460 non-null int64
BsmtUnfSF       1460 non-null int64
TotalBsmtSF     1460 non-null int64
1stFlrSF        1460 non-null int64
2ndFlrSF        1460 non-null int64
LowQualFinSF    1460 non-null int64
GrLivArea       1460 non-null int64
BsmtFullBath    1460 non-null int64
BsmtHalfBath    1460 non-null int64
FullBath        1460 non-null int64
HalfBath        1460 non-null int64
BedroomAbvGr    1460 non-null int64
KitchenAbvGr    1460 non-null int64
TotRmsAbvGrd    1460 non-null int64
dtypes: int64(15)
memory usage: 171.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 4 columns):
Foundation    1460 non-null object
Heating       1460 non-null object
CentralAir    1460 non-null object
Electrical    1459 non-null object
dtypes: object(4)
memory usage: 45.7+ KB
<class 'pandas.core.frame

In [61]:
# numerical은 결측치 없음
# categorical은 결측치를 하나의 unique갑으로 보고 0에 대응시킴
df2[cols_categorical] = df2[cols_categorical].fillna(0)
# ordinal은 data description에 따라 NA = 0인 경우 0 처리
df2[cols_ordinal[:4]] = df2[cols_ordinal[:4]].fillna(0)
# 설명이 없을 경우 0.5로 처리
df2[cols_ordinal[4:]] = df2[cols_ordinal[4:]].fillna(0.5)

In [62]:
df2.isnull().sum()

Unnamed: 0      0
Foundation      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinSF1      0
BsmtFinType2    0
BsmtFinSF2      0
BsmtUnfSF       0
TotalBsmtSF     0
Heating         0
HeatingQC       0
CentralAir      0
Electrical      0
1stFlrSF        0
2ndFlrSF        0
LowQualFinSF    0
GrLivArea       0
BsmtFullBath    0
BsmtHalfBath    0
FullBath        0
HalfBath        0
BedroomAbvGr    0
KitchenAbvGr    0
KitchenQual     0
TotRmsAbvGrd    0
dtype: int64

In [65]:
# df2['Electrical'][df2['Electrical'].isnull() == True]

Series([], Name: Electrical, dtype: object)

## 수치화

In [108]:
# 카테고리형
for col in df2[cols_categorical]:
    val = 1
    temp_dict = {}
    for unique in df2[col].unique():
        if unique != 0:
            temp_dict[unique] = val
            df2[col][df2[col] == unique] = val
            val += 1
    print(temp_dict)
# df2.loc[:,['Foundation','Heating', 'CentralAir', 'Electrical']]

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6}
{1: 1, 2: 2}
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}


In [91]:
# 서수형
df_temp = df2[['BsmtQual', 'BsmtCond', 'HeatingQC', 'KitchenQual']]
for col in df_temp:    
    df2[col][df2[col] == 'Ex'] = (5 - 1/2) / 5
    df2[col][df2[col] == 'Gd'] = (4 - 1/2) / 5
    df2[col][df2[col] == 'TA'] = (3 - 1/2) / 5
    df2[col][df2[col] == 'Fa'] = (2 - 1/2) / 5
    df2[col][df2[col] == 'Po'] = (1 - 1/2) / 5
    print(df2[col].unique())

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a

[0.7 0.5 0.9 0 0.3]
[0.5 0.7 0 0.3 0.1]
[0.9 0.7 0.5 0.3 0.1]
[0.7 0.5 0.9 0.3]


In [83]:
df2['BsmtExposure'].unique()

df2['BsmtExposure'][df2['BsmtExposure']=='Gd'] = (4 - 1/2) / 4
df2['BsmtExposure'][df2['BsmtExposure']=='Av'] = (3 - 1/2) / 4
df2['BsmtExposure'][df2['BsmtExposure']=='Mn'] = (2 - 1/2) / 4
df2['BsmtExposure'][df2['BsmtExposure']=='No'] = (1 - 1/2) / 4

df2['BsmtExposure'].unique()

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Python\Anaconda3\lib\site-packages\ipy

array([0.125, 0.875, 0.375, 0.625, 0], dtype=object)

In [84]:
df2['BsmtFinType1'].unique()

df2['BsmtFinType1'][df2['BsmtFinType1']=='GLQ'] = (6 - 1/2) / 6
df2['BsmtFinType1'][df2['BsmtFinType1']=='ALQ'] = (5 - 1/2) / 6
df2['BsmtFinType1'][df2['BsmtFinType1']=='BLQ'] = (4 - 1/2) / 6
df2['BsmtFinType1'][df2['BsmtFinType1']=='Rec'] = (3 - 1/2) / 4
df2['BsmtFinType1'][df2['BsmtFinType1']=='LwQ'] = (2 - 1/2) / 4
df2['BsmtFinType1'][df2['BsmtFinType1']=='Unf'] = (1 - 1/2) / 4

df2['BsmtFinType1'].unique()

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Python\Anaconda3\lib\site-packages\ipy

array([0.9166666666666666, 0.75, 0.125, 0.625, 0.5833333333333334, 0,
       0.375], dtype=object)

In [85]:
df2['BsmtFinType2'].unique()

df2['BsmtFinType2'][df2['BsmtFinType2']=='GLQ'] = (6 - 1/2) / 6
df2['BsmtFinType2'][df2['BsmtFinType2']=='ALQ'] = (5 - 1/2) / 6
df2['BsmtFinType2'][df2['BsmtFinType2']=='BLQ'] = (4 - 1/2) / 6
df2['BsmtFinType2'][df2['BsmtFinType2']=='Rec'] = (3 - 1/2) / 4
df2['BsmtFinType2'][df2['BsmtFinType2']=='LwQ'] = (2 - 1/2) / 4
df2['BsmtFinType2'][df2['BsmtFinType2']=='Unf'] = (1 - 1/2) / 4

df2['BsmtFinType2'].unique()

C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Python\Anaconda3\lib\site-packages\ipy

array([0.125, 0.5833333333333334, 0.5, 0.75, 0.625, 0.375,
       0.9166666666666666], dtype=object)

## 표준화
정확히는 Standardization: (요소값 - 평균)/표준편차 <p>
Normalization: (요소값 - 최소값)/(최대값 - 최소값)


In [105]:
# 수치형 데이터
for col in cols_numerical:
    df2[col] = (df2[col] - df2[col].mean()) / df2[col].std()
df2[cols_numerical].head(10)

BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  1stFlrSF  2ndFlrSF  \
0    0.575228   -0.288554  -0.944267    -0.459145 -0.793162  1.161454   
1    1.171591   -0.288554  -0.641008     0.466305  0.257052 -0.794891   
2    0.092875   -0.288554  -0.301540    -0.313261 -0.627611  1.188943   
3   -0.499103   -0.288554  -0.061648    -0.687089 -0.521555  0.936955   
4    0.463410   -0.288554  -0.174805     0.199611 -0.045596  1.617323   
5    0.632233   -0.288554  -1.138896    -0.595911 -0.948366  0.501703   
6    2.028862   -0.288554  -0.566325     1.432785  1.374522 -0.794891   
7    0.910682   -0.090190  -0.794901     0.112993 -0.143892  1.456967   
8   -0.972685   -0.288554   0.870759    -0.240320 -0.363764  0.927792   
9    0.893142   -0.288554  -0.966898    -0.151422 -0.221494 -0.794891   

   LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  \
0     -0.120201   0.370207      1.107431     -0.240978  0.789470  1.227165   
1     -0.120201  -0.482347     -0.819684      3.947457  0.789470 -0.761360   
2     -0.120201   0.514836      1.107431     -0.240978  0.789470  1.227165   
3     -0.120201   0.383528      1.107431     -0.240978 -1.025689 -0.761360   
4     -0.120201   1.298881      1.107431     -0.240978  0.789470  1.227165   
5     -0.120201  -0.292045      1.107431     -0.240978 -1.025689  1.227165   
6     -0.120201   0.339758      1.107431     -0.240978  0.789470 -0.761360   
7     -0.120201   1.093354      1.107431     -0.240978  0.789470  1.227165   
8     -0.120201   0.492000     -0.819684     -0.240978  0.789470 -0.761360   
9     -0.120201  -0.834405      1.107431     -0.240978 -1.025689 -0.761360   

   BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd  
0      0.163723     -0.211381      0.911897  
1      0.163723     -0.211381     -0.318574  
2      0.163723     -0.211381     -0.318574  
3      0.163723     -0.211381      0.296662  
4      1.389547     -0.211381      1.527133  
5     -2.287924     -0.211381     -0.933810  
6      0.163723     -0.211381      0.296662  
7      0.163723     -0.211381      0.296662  
8     -1.062101      4.327097      0.911897  
9     -1.062101      4.327097     -0.933810

In [107]:
# 결과 확인
df2.head()

Unnamed: 0 Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  \
0           0          1      0.7      0.5        0.125     0.916667   
1           1          2      0.7      0.5        0.875         0.75   
2           2          1      0.7      0.5        0.375     0.916667   
3           3          3      0.5      0.7        0.125         0.75   
4           4          1      0.7      0.5        0.625     0.916667   

   BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF      ...       LowQualFinSF  \
0    0.575228        0.125   -0.288554  -0.944267      ...          -0.120201   
1    1.171591        0.125   -0.288554  -0.641008      ...          -0.120201   
2    0.092875        0.125   -0.288554  -0.301540      ...          -0.120201   
3   -0.499103        0.125   -0.288554  -0.061648      ...          -0.120201   
4    0.463410        0.125   -0.288554  -0.174805      ...          -0.120201   

  GrLivArea BsmtFullBath BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0  0.370207     1.107431    -0.240978  0.789470  1.227165      0.163723   
1 -0.482347    -0.819684     3.947457  0.789470 -0.761360      0.163723   
2  0.514836     1.107431    -0.240978  0.789470  1.227165      0.163723   
3  0.383528     1.107431    -0.240978 -1.025689 -0.761360      0.163723   
4  1.298881     1.107431    -0.240978  0.789470  1.227165      1.389547   

   KitchenAbvGr  KitchenQual  TotRmsAbvGrd  
0     -0.211381          0.7      0.911897  
1     -0.211381          0.5     -0.318574  
2     -0.211381          0.7     -0.318574  
3     -0.211381          0.7      0.296662  
4     -0.211381          0.7      1.527133  

[5 rows x 27 columns]

In [109]:
df2.to_csv('./data/HousePrice_preprocessing_df2', sep=',', encoding='UTF-8')
! dir data

 C 드라이브의 볼륨: BOOTCAMP
 볼륨 일련 번호: 5415-72D5

 C:\Users\JuhnnyKo\Dropbox\Anaconda_src\HousePrice\data 디렉터리

2018-11-27  오후 12:08    <DIR>          .
2018-11-27  오후 12:08    <DIR>          ..
2018-05-28  오후 02:49            13,370 data_description.txt
2018-11-26  오후 11:37            19,362 data_description_translate.txt
2018-11-27  오전 12:08           131,663 HousePrice_df2
2018-11-27  오후 12:08           516,364 HousePrice_preprocessing_df2
2018-05-28  오후 02:49            31,939 sample_submission.csv
2018-05-28  오후 02:49            15,685 sample_submission.csv.gz
2018-05-28  오후 02:49           451,405 test.csv
2018-05-28  오후 02:49            83,948 test.csv.gz
2018-05-28  오후 02:49           460,676 train.csv
2018-05-28  오후 02:49            91,387 train.csv.gz
              10개 파일           1,815,799 바이트
               2개 디렉터리   5,675,294,720 바이트 남음
